# Generated by Django 3.1 on 2020-08-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seach',
            new_name='Search',
        ),
    ]
