# Generated by Django 3.1 on 2020-08-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200806_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
